baseURL = 'http://example.com/'
# languageCode = 'en'
languageCode = 'pt-br'
# languageCode = 'zh-CN'
theme = "JuiceBar"
title = "BotecoDev"

[params]
author = "L3onix"
description = "Blog pessoal"
authorImage = "/images/profile.jpg"
paginate = 5

Title = "BotecoDev"
content = "Meu nome é Leonardo, bem vindo ao BotecoDev!   "
imageUrl = "https://media.licdn.com/dms/image/D4D03AQEMHv9DrrU3gA/profile-displayphoto-shrink_800_800/0/1666728852457?e=1705536000&v=beta&t=oOOLIlKmJAlFBEFVSN_XHUAAjimmsXf8QpFyIdhw1yA"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "Github"
url = "https://github.com/l3onix"
# [[params.social]]
# name = "telegram"
# url = "https://t.me/Hotjuice"
# [[params.social]]
# name = "twitter"
# url = "https://twitter.com/hotjuicee"
[[params.social]]
name = "email"
url = "mailto:leonardo.fm00@gmail.com"

[taxonomies]
category = "categories"

# To add a new navigation link
[[menu.main]]
name = "Sobre"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categorias"
url = "/categories"

[params.giscus]
repo = "hotjuicew/blog"
repoID = "R_kgDOHHQOuw"
category = "Announcements"
categoryID = "DIC_kwDOHHQOu84CWCQ3"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]



